[package]
name = "serve"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[features]
cuda = ["autoagents-serve/cuda"]
metal = ["autoagents-serve/metal"]

[dependencies]
autoagents = { workspace = true, features = ["logging"] }
autoagents-serve = { workspace = true, features = ["search-tools"] }
tokio = { workspace = true }
clap = { workspace = true, features = ["derive"] }
tokio-stream = { workspace = true }
serde_json = { workspace = true }

anyhow = "1.0"
